[tool.poetry]
name = "calibration"
version = "0.1.0"
description = ""
authors = ["Luke Burgess <lburgess1@student.unimelb.edu.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
